[package]
name = "slide24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
iterator-sorted = "0.2.0"
macroquad = "0.4.5"
miniquad = "0.4.0"
sapp-wasm = "0.1.26"
